---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  python_interpreter:
    package_system: python3.11 python3.11-cryptography
    python_path: /usr/bin/python3.11

  ansible_core:
    package_pip: ansible-core>=2.15.0rc2,<2.16

  ansible_runner:
    package_pip: ansible-runner

  galaxy: |
    ---
    collections:
      # IBM Power
      - name: ibm.power_hmc
      - name: ibm.power_aix
      - name: ibm.power_vios
      - name: ibm.power_ibmi
      - name: enfence.powerha_aix
      - name: ibm.powervc

      # UNIX/Linux utilities
      - name: ansible.posix
      - name: community.general
      - name: community.crypto
      - name: community.network
      - name: ansible.utils

      # Insights
      - name: redhatinsights.insights

  system: |
    sshpass
    rsync
    python3.11-devel
    gcc
    libffi-devel
    openssl-devel
    unzip
    git
    krb5-devel
    krb5-workstation
    libxml2-devel
    libxslt-devel
    libatomic
  python: |
    paramiko
    pyOpenSSL
    pyyaml
    six
    pexpect
    wheel
    setuptools

additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install --upgrade pip wheel setuptools
    - RUN dnf -y update && dnf clean all
  append_final:
    - RUN alternatives --install /usr/bin/python python /usr/bin/python3.11 311
