---
version: 3
images:
  base_image:
    name: docker.io/rockylinux:9
dependencies:
  python_interpreter:
    package_system: python3.11 python3.11-cryptography
    python_path: /usr/bin/python3.11

  ansible_core:
    package_pip: ansible-core>=2.15.0rc2,<2.16

  ansible_runner:
    package_pip: ansible-runner

  galaxy: |
    ---
    collections:
      # IBM Power
      - name: ibm.power_hmc
      - name: ibm.power_aix
      - name: ibm.power_vios
      - name: ibm.power_ibmi
      - name: enfence.powerha_aix
      - name: ibm.power_ha
      - name: ibm.powervc
      - name: ibm.power_aix_oracle
      - name: ibm.power_aix_oracle_dba
      - name: ibm.power_aix_oracle_rac_asm
      - name: openstack.cloud
      - name: awx.awx
      # UNIX/Linux utilities
      - name: ansible.posix
      - name: community.general
      - name: ansible.utils

  system: |
    git-core [platform:rpm]
    python3.11-devel [platform:rpm compile]
    python3.11-cryptography [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    redhat-rpm-config [platform:rpm compile]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    unzip [platform:rpm]
    podman-remote [platform:rpm]
    epel-release [platform:rpm]
    cmake [platform:rpm compile]
    gcc [platform:rpm compile]
    gcc-c++ [platform:rpm compile]
    gcc-toolset-12 [platform:rpm compile]
    make [platform:rpm compile]
    openssl-devel [platform:rpm compile]
    rust [platform:rpm compile]
    libffi-devel [platform:rpm compile]
    libxml2-devel [platform:rpm arch:ppc64le compile]
    libxslt-devel [platform:rpm arch:ppc64le compile]
  python: |
    paramiko
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    pywinrm[kerberos,credssp]
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install --upgrade pip wheel setuptools
    - RUN dnf -y update && dnf clean all
  append_final:
    - RUN alternatives --install /usr/bin/python python /usr/bin/python3.11 311
