---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9
dependencies:
  python_interpreter:
    package_system: python3.11 python3.11-cryptography
    python_path: /usr/bin/python3.11
  ansible_core:
    package_pip: ansible-core>=2.15.0rc2,<2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    ---
    collections:
      - name: ibm.power_hmc
      - name: ibm.power_aix
      - name: ibm.power_vios
      - name: ibm.power_ibmi
      - name: enfence.powerha_aix
      - name: ibm.powervc
      - name: ansible.posix
      - name: community.general
      - name: community.crypto
      - name: community.network
      - name: ansible.utils
      - name: redhatinsights.insights
  system: |
    git-core [platform:rpm]
    python3.11-devel [platform:rpm compile]
    python3.11-cryptography [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    redhat-rpm-config [platform:rpm compile]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    unzip [platform:rpm]
    podman-remote [platform:rpm]
    epel-release [platform:rpm]
    cmake [platform:rpm compile]
    gcc [platform:rpm compile]
    gcc-c++ [platform:rpm compile]
    gcc-toolset-12 [platform:rpm compile]
    make [platform:rpm compile]
    openssl-devel [platform:rpm compile]
    rust [platform:rpm compile]
    libffi-devel [platform:rpm compile]
    libxml2-devel [platform:rpm arch:ppc64le compile]
    libxslt-devel [platform:rpm arch:ppc64le compile]
  python: |
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    pywinrm[kerberos,credssp]
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
    receptorctl
additional_build_steps:
  append_base:
    - RUN dnf -y update && dnf clean all
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
    - RUN alternatives --install /usr/bin/python python /usr/bin/python3.11 311
